### PR TITLE
Nav clean up

### PR DESCRIPTION
**Pull request by Lars-Kish**
Pull request to merge NavCleanUp into dev branch. Covering issues 19 (Get webui offline), 16 (Single source data visualization), 15 (Add way to remove or organize waypoints), 14 (Show rover heading).

Get WebUI Offline - All JS libraries used now reference a local copy. 2 different tile sets have been added. Entire WebUI is now able to run offline.

Single Source Data Vis - Gauge component was added. Gauges can be made on the fly as needed. Parameters used are dataSource, minValue, maxValue and an optional parameter for units. CarDashCluster component was added for a basic gauge cluster. Contains Speed, heading and current draw gauges currently.

Organize and Delete Waypoints - Waypoints list now has delete button and is draggable to change order. When deleting, waypoints will instantly reorder if deleted was in the middle. Id's and array will change instantly. When changing order, drag and drop to change. The ID displayed on the list will not update but the array will be reordered and the popup id will change. Lat and Long also added to the list. Reorder should be tested to make sure it works how you would like it to (I think it's good but it might not be how you wanted it to work).

Show Rover Heading - Rover heading now shows up on the map. Data is requested from the server in degrees. Icon was changed to a triangle and rotates from the centre (centre origin). Heading is updated at the same time as location is.

### CODE REVIEW

**Review by ottopasuuna — CHANGES_REQUESTED** [review]
Looks great!
Could you change the dials in the dash (heading, etc.) to update every 100ms? We'll need to be able to watch those things in real time.

**Comment by Lars-Kish** [comment]
Refresh time has been changed to 100ms for the cluster.

**Review by ottopasuuna — APPROVED** [review]

**Comment by ottopasuuna** [comment]
Awesome, thanks. Feel free to hit the merge button!

**Comment by Lars-Kish** [comment]
Merged! Do I delete the branch as well now?

**Comment by ottopasuuna** [comment]
Yeah, you can delete the branch.

**Pull request merged**
